# Generated by Django 3.2.23 on 2024-01-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="discription",
            field=models.CharField(
                help_text="Describe your room ( maximum letters 150 )", max_length=150
            ),
        ),
    ]
