# Generated by Django 5.0.1 on 2024-02-04 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_pictures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Likes",
            ),
        ),
    ]
