# Generated by Django 4.2.3 on 2023-07-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="background",
            field=models.ImageField(
                blank=True, null=True, upload_to="rooms_background/"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="discription",
            field=models.TextField(blank=True),
        ),
    ]
