# Generated by Django 4.2.3 on 2023-07-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_room_background_alter_room_discription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="background",
            field=models.ImageField(
                blank=True,
                help_text="Set a background ( Optional )",
                null=True,
                upload_to="rooms_background/",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="discription",
            field=models.TextField(
                blank=True, help_text="Describe your room ( Optional )"
            ),
        ),
    ]
