# Generated by Django 5.0.1 on 2024-02-04 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_picture_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Likes",
            ),
        ),
    ]
