# Generated by Django 3.2.23 on 2024-01-17 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0003_auto_20240117_1213"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
