# Generated by Django 5.0.1 on 2024-03-01 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_room_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="discription",
            new_name="description",
        ),
    ]
