# Generated by Django 4.2.3 on 2023-07-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_alter_room_background_alter_room_discription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(
                help_text="Enter a name for the Room", max_length=150, unique=True
            ),
        ),
    ]
