# Generated by Django 4.2.3 on 2023-08-01 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_alter_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-created_at"]},
        ),
    ]
