# Generated by Django 5.0.1 on 2024-01-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_alter_room_name"),
        ("tags", "0002_alter_tags_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="tags",
            field=models.ManyToManyField(to="tags.tags", verbose_name="Tags"),
        ),
    ]
