# Generated by Django 5.0.1 on 2024-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0006_room_tags"),
        ("tags", "0002_alter_tags_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="tags",
            field=models.ManyToManyField(
                related_name="rooms", to="tags.tags", verbose_name="Tags"
            ),
        ),
    ]
