# Generated by Django 5.0.1 on 2024-01-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0009_alter_room_tags"),
        ("tags", "0003_tag_delete_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to="tags.tag", verbose_name="Tags"
            ),
        ),
    ]
