# Generated by Django 5.0.1 on 2024-02-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="Profile picture",
            ),
        ),
    ]
