# Generated by Django 4.2.3 on 2023-08-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(
                default=models.CharField(
                    help_text="Write a short bio about yourself ( required )",
                    max_length=1000,
                ),
                max_length=150,
            ),
        ),
    ]
