# Generated by Django 5.0.1 on 2024-01-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("DESIGNER", "Designer"), ("NORMAL", "Normal")],
                default="NORMAL",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
