# Generated by Django 4.2.3 on 2023-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discription",
            field=models.CharField(
                help_text="Write a short bio about yourself ( Optional )",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to="profiles/"),
        ),
    ]
