# Generated by Django 5.0.1 on 2024-01-22 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_picture",
            new_name="picture",
        ),
    ]
