# Generated by Django 5.0.1 on 2024-02-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_picture"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designermore",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="designers", to="tags.tag", verbose_name="Tags"
            ),
        ),
    ]
