# Generated by Django 4.2.3 on 2023-07-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_discription_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discription",
            field=models.CharField(
                blank=True,
                help_text="Write a short bio about yourself ( Optional )",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
