# Generated by Django 4.2.3 on 2023-08-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(max_length=150),
        ),
    ]
