# Generated by Django 5.0.1 on 2024-01-25 09:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_profile_picture_user_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Normal",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Birth Date"),
        ),
    ]
