# Generated by Django 5.0.1 on 2024-02-04 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_designermore_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follow",
            field=models.ManyToManyField(
                related_name="follower", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
