# Generated by Django 5.0.1 on 2024-02-04 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follow",
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
