# Generated by Django 5.0.1 on 2024-01-25 13:14

import accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_normal_user_birth_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignerMore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorate_application",
                    models.CharField(
                        max_length=100, verbose_name="Favorate Application"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Normal",
        ),
        migrations.CreateModel(
            name="Designer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", accounts.managers.DesignersManager()),
            ],
        ),
        migrations.CreateModel(
            name="NormalUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", accounts.managers.NormalUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("DESIGNER", "Designer"),
                    ("NORMAL", "Normal"),
                    ("SYSTEM", "System"),
                ],
                default="NORMAL",
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="designermore",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
