# Generated by Django 5.0.1 on 2024-01-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_designermore_delete_normal_designer_normaluser_and_more"),
        ("tags", "0003_tag_delete_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="designermore",
            name="tags",
            field=models.ManyToManyField(
                null=True, related_name="designers", to="tags.tag", verbose_name="Tags"
            ),
        ),
    ]
