# Generated by Django 5.0.1 on 2024-01-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_designermore_tags"),
        ("tags", "0003_tag_delete_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designermore",
            name="tags",
            field=models.ManyToManyField(
                related_name="designers", to="tags.tag", verbose_name="Tags"
            ),
        ),
    ]
