def debug(message):
    print()
    print("#" * 150)
    print()
    print("#" * 150)
    print()
    print("#" * 50, "DIR", "#" * 50)
    print()
    print(dir(message))
    print()
    print("#" * 50, "Message", "#" * 50)
    print()
    print(message)
    print()
    print("#" * 150)
    print()
