# Generated by Django 5.0.1 on 2024-01-23 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("designers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designermore",
            name="discription",
        ),
    ]
