# Generated by Django 5.0.1 on 2024-01-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designers", "0002_remove_designermore_discription"),
    ]

    operations = [
        migrations.AddField(
            model_name="designermore",
            name="favorate_application",
            field=models.CharField(
                default="Adobe", max_length=100, verbose_name="Favorate Application"
            ),
        ),
    ]
