# Generated by Django 5.0.1 on 2024-01-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
