# Generated by Django 5.0.1 on 2024-01-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0009_alter_room_tags"),
        ("tags", "0002_alter_tags_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
