# Generated by Django 5.0.1 on 2024-02-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0003_tag_delete_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=150, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
